import js from "@eslint/js";
import globals from "globals";

export default [
  {
    ignores: [
      "node_modules/**",
      "docs/**",
      "*.watch.mjs",
      // Generated by build.mjs from src/ — lint the source, not the artifact.
      "plugin.js",
    ],
  },
  js.configs.recommended,
  {
    files: ["**/*.js", "**/*.mjs"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        ...globals.browser,
        ...globals.es2022,
      },
    },
    rules: {
      "no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          // `const { chat_pin, ...rest } = entry` is the omit-a-key idiom; the
          // named bindings are intentionally discarded, not dead code.
          ignoreRestSiblings: true,
        },
      ],
      "no-undef": "error",
      "no-console": "off",
    },
  },
  {
    // groups.mjs, lib/, tests, and the build script are Node, not browser.
    files: ["groups.mjs", "lib/**/*.mjs", "tests/**/*.mjs", "build.mjs"],
    languageOptions: {
      globals: { ...globals.node },
    },
  },
];
