import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'
import vm from 'node:vm'
const source = readFileSync(new URL('../plugin.js', import.meta.url), 'utf8')
function runtime(query = {}) { const atom = value => ({ get: () => value, set: () => undefined }); const jsx = (type, props = {}) => ({ type, props }); const context = { atom, jsx, jsxs: jsx, useQuery: () => query, useValue: value => value?.get ? value.get() : value, useState: value => [value, () => undefined], Button: 'Button', BotFace: 'BotFace', GlyphSpinner: 'GlyphSpinner', EditProfileDialog: 'EditProfileDialog', profileColor: () => '#000', PALETTE_AREA: 'palette', COMPOSER_AREAS: { middleware: 'middleware' }, document: { getElementById: () => null, createElement: () => ({}), head: { appendChild: () => undefined } }, host: { state: { profile: { get: () => 'ops', listen: () => undefined } }, request: () => undefined } }; const code = source.replace(/^import\s+\{[\s\S]*?\}\s+from '@hermes\/plugin-sdk'\r?\n/m, '').replace(/^import .* from 'react'\r?\n/m, '').replace(/^import .* from 'react\/jsx-runtime'\r?\n/m, '').replace('export default {', 'globalThis.plugin = {').concat('\nglobalThis.__ProfilePane = ProfilePane;\n'); vm.runInNewContext(code, context); return context }
function textOf(node) { return node == null ? '' : typeof node === 'string' ? node : typeof node === 'object' ? Object.values(node).map(textOf).join(' ') : '' }
test('unit: ProfilePane uses the active profile summary query', () => assert.match(source, /queryKey: \[ID, 'profile-summary', name\]/))
test('integration: ProfilePane renders provider, model, skills, and tools', () => { const tree = runtime({ data: { model: { provider: 'nous', default: 'model-x' }, description: 'Planner', skills: [{ name: 'search', enabled: true }], toolsets: [{ name: 'shell', enabled: true }] }, isLoading: false }).__ProfilePane(); assert.match(textOf(tree), /nous.*model-x.*Planner.*search.*shell/) })
test('regression: Profile registration docks beside Routines', () => assert.match(source, /id: 'profile'[\s\S]*dock: \{ pane: 'routines', pos: 'right' \}/))
test('system: plugin registration exposes the Profile pane', () => { const r = runtime(); const entries = []; r.plugin.register({ storage: { get: () => null }, register: item => entries.push(item) }); assert.equal(entries.some(item => item.id === 'profile' && item.title === 'Profile'), true) })
test('performance: summary query key stays bounded', () => { const start = Date.now(); for (let i = 0; i < 10000; i += 1) ['hermes-bots', 'profile-summary', 'ops'].join(':'); assert.ok(Date.now() - start < 1000) })